#pragma once

#define PERMISSIVE_HOLD
#define TAPPING_TERM_PER_KEY
#define LEADER_NO_TIMEOUT
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
// #define LEADER_PER_KEY_TIMING
// #define LEADER_TIMEOUT 300
